# Configuration of py.test
[pytest]
addopts=-v
        -s -n auto
        # -x
        # --pep8
        --cov=falcon_limiter
        --cov-fail-under 78
        --showlocals
        --disable-pytest-warnings
        --ignore=docs

# Running all tests should take less than 12 minutes.
# Otherwise, something went wrong.
timeout = 720
