name: Run tests

on:
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  run_test:
    name: Python ${{matrix.python-version}} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os:
          - "ubuntu-latest"

    # Steps to run in each job.
    # Some are GitHub actions, others run shell commands.
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmemcached-dev memcached redis-server redis-sentinel python3-dev
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
          pipenv run python --version
          pipenv run pip list

      - name: Test with pytest
        run: |
          pipenv run pytest --cov-report term-missing
