name: Run tests

on:
  # Trigger the tests workflow on push on all branches, but
  # for pull request only on the master branch
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  run_tox:
    name: tox -e ${{ matrix.toxenv }} (${{matrix.python-version}} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
        os:
          - "ubuntu-20.04"
#        toxenv:
#          - "py38"
#          - "look"
#          - "asgilook"
#          - "check_vendored"
#          - "twine_check"
#          - "daphne"
#          - "hypercorn"
#          - "e2e_chrome"
#          - "e2e_firefox"
#          - "no_optional_packages"
#          - "wsgi_servers"
        include:
          - python-version: pypy3
            os: ubuntu-20.04
            toxenv: pypy3
          - python-version: 3.6
            os: ubuntu-20.04
            toxenv: py36
          - python-version: 3.6
            os: ubuntu-20.04
            toxenv: py36_cython
          - python-version: 3.7
            os: ubuntu-20.04
            toxenv: py37
          - python-version: 3.9
            os: ubuntu-20.04
            toxenv: py39
          - python-version: 3.9
            os: ubuntu-20.04
            toxenv: py39_cython
          - python-version: "3.10"
            os: ubuntu-20.04
            toxenv: py310
          - python-version: "3.10"
            os: ubuntu-20.04
            toxenv: py310_cython
          - python-version: 3.8
            os: ubuntu-20.04
            toxenv: py38_sans_msgpack
          - python-version: 3.8
            os: macos-latest
            toxenv: py38_nocover
          - python-version: 3.8
            os: windows-latest
            toxenv: py38_nocover

    # Steps to run in each job.
    # Some are GitHub actions, others run shell commands.
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmemcached-dev memcached redis-server
          python -m pip install --upgrade pip
          pip install -U coverage setuptools tox wheel pipenv codecov
          python --version
          pip --version
          pipenv --version
          tox --version
          coverage --version
          pipenv install --dev
          # importlib-metadata is needed for Python 3.6 and 3.7
          pipenv install --dev importlib-metadata

      - name: Run tests
        # run: tox -e ${{ matrix.toxenv }}
        run: tox -e py

#      - name: Test with pytest
#        run: |
#          pytest --cov-report term-missing

      - name: Combine coverage
        #if: ${{ matrix.toxenv == 'py35' || matrix.toxenv == 'py38' || matrix.toxenv == 'py38_sans_msgpack' }}
        run: |
          coverage --version
          coverage combine

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        #if: ${{ matrix.toxenv == 'py35' || matrix.toxenv == 'py38' || matrix.toxenv == 'py38_sans_msgpack' }}
        with:
          env_vars: PYTHON
          fail_ci_if_error: true
